# Generated by Django 3.2.3 on 2022-08-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0008_alter_noticia_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('L', 'Leitor'), ('E', 'Editor')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='comentarios',
            field=models.ManyToManyField(related_name='comentarios', through='jornal.Comentario', to='jornal.Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagem',
            field=models.ImageField(null=True, upload_to='autores'),
        ),
    ]
