# Generated by Django 3.2.3 on 2022-08-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0010_auto_20220802_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='texto',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='comentarios',
            field=models.ManyToManyField(related_name='comentarios', through='jornal.Comentario', to='jornal.Usuario'),
        ),
    ]
