# Generated by Django 3.2.3 on 2022-08-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0011_auto_20220802_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicao',
            name='data_fim',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='edicao',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='comentarios',
            field=models.ManyToManyField(related_name='comentarios', through='jornal.Comentario', to='jornal.Usuario'),
        ),
    ]
